version: '3.9'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: es01
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx2g -Xmx2g"
    ports:
      - "9200:9200"
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:latest
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elastic

networks:
  elastic:
    driver: bridge